import { Inter } from "next/font/google";
import "../ui/globals.css";
import GlobalNav from "../ui/grobalnav.tsx"; //これは問題になるかも

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Conduit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalNav />
        {children}
      </body>
    </html>
  );
}
